/**
 * Fetch the Material Symbols shapes the app uses and write icons.ts.
 *
 * The design (ADR-0019) draws its icons with the Material Symbols web font
 * from Google's CDN. A font from another origin is not there when the app opens
 * offline (ADR-0018), and when it fails the browser shows the icon's name as
 * words in the middle of the screen. So the shapes are copied into the
 * repository as path data, once, by this script.
 *
 * Run it only when an icon is added or removed:
 *
 *     node scripts/fetch-icons.mjs
 *
 * It needs the network, which is why its output is committed and the app never
 * runs it. Every shape comes from google/material-design-icons, Apache-2.0.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const BASE =
  "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web";

/**
 * The icons the screens use, and where each one appears. A name with `fill`
 * also gets the solid variant, which the design uses for a state that is
 * settled: a confirmed record, a chosen row.
 */
const ICONS = [
  { name: "account_balance", why: "the labour office" },
  { name: "add", why: "start a new offer, a new account" },
  { name: "arrow_back", why: "go back one screen" },
  { name: "arrow_forward", why: "go on to the next screen" },
  { name: "backspace", why: "clear one digit" },
  { name: "badge", why: "a person's own record" },
  { name: "calendar_month", why: "a date range on a work record" },
  { name: "call", why: "open the dialler, for the officer only" },
  { name: "check", why: "a small tick inside a chosen row" },
  { name: "check_circle", why: "both sides agree", fill: true },
  { name: "chevron_left", why: "previous page of a list" },
  { name: "chevron_right", why: "open this record" },
  { name: "close", why: "close a panel" },
  { name: "distance", why: "how far away the work is" },
  { name: "domain", why: "a business in the directory" },
  { name: "engineering", why: "a contractor" },
  { name: "error", why: "the server refused the action", fill: true },
  { name: "expand_more", why: "a list that opens, such as the language list" },
  { name: "gavel", why: "a complaint, and the officer's decision" },
  { name: "groups", why: "several workers" },
  { name: "info", why: "a note that explains, not warns" },
  { name: "install_mobile", why: "the install button (ADR-0018)" },
  { name: "key_vertical", why: "the handover code" },
  { name: "language", why: "choose the language (ADR-0015)" },
  { name: "location_city", why: "a town" },
  { name: "location_on", why: "where the work is", fill: true },
  { name: "lock", why: "terms are sealed, the PIN" },
  { name: "logout", why: "sign out" },
  { name: "payments", why: "money paid" },
  { name: "person", why: "a worker" },
  { name: "person_add", why: "the officer creates an account" },
  { name: "progress_activity", why: "waiting for the server" },
  { name: "receipt_long", why: "the record list" },
  { name: "schedule", why: "waiting for the other side to answer" },
  { name: "support_agent", why: "the Ask for help tab" },
  { name: "search", why: "search for a town, a name" },
  { name: "send", why: "send the offer, send the code" },
  { name: "shield", why: "a warning about keeping the PIN secret" },
  { name: "sms", why: "the message that went to the worker's phone" },
  { name: "verified_user", why: "a checked record" },
  { name: "visibility", why: "see the digits that are hidden" },
  { name: "warning", why: "the worker says this row is wrong", fill: true },
  { name: "work", why: "the Find work tab" },
];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "src/shared/components/icons.ts");

/** The `d` attribute of the single path in one Material Symbols file. */
async function shape(name, filled) {
  const variant = filled ? "_fill1" : "";
  const url = `${BASE}/${name}/materialsymbolsoutlined/${name}${variant}_24px.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  const svg = await res.text();

  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) {
    throw new Error(`${name}${variant} has ${paths.length} paths, expected 1`);
  }
  const box = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (box !== "0 -960 960 960") {
    throw new Error(`${name}${variant} has viewBox "${box}", expected "0 -960 960 960"`);
  }
  return paths[0];
}

const entries = [];
for (const icon of ICONS.sort((a, b) => a.name.localeCompare(b.name))) {
  const outlined = await shape(icon.name, false);
  const filled = icon.fill ? await shape(icon.name, true) : null;
  entries.push({ ...icon, outlined, filled });
  process.stdout.write(`${icon.name}${filled ? " (+filled)" : ""}\n`);
}

const lines = [
  "/*",
  " * Material Symbols path data, copied into the repository.",
  " *",
  " * Generated by scripts/fetch-icons.mjs. Do not edit by hand: add the name to",
  " * that script's list and run it again.",
  " *",
  " * Shapes from google/material-design-icons, Apache License 2.0. Every path",
  " * is drawn in a 960 box with the y axis starting at -960, which is why the",
  " * viewBox in Icon.tsx is \"0 -960 960 960\".",
  " */",
  "",
  "/** One icon: the outlined shape, and the solid one where a screen needs it. */",
  "export type IconShape = { outlined: string; filled?: string };",
  "",
  "export const ICONS: Record<string, IconShape> = {",
];
for (const e of entries) {
  lines.push(`  // ${e.why}`);
  lines.push(`  ${e.name}: {`);
  lines.push(`    outlined: "${e.outlined}",`);
  if (e.filled) lines.push(`    filled: "${e.filled}",`);
  lines.push(`  },`);
}
lines.push("};", "");

writeFileSync(OUT, lines.join("\n"));
process.stdout.write(`\n${entries.length} icons written to ${OUT}\n`);
