import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma";
import { requireAuth } from "../lib/auth";
import { computeBalance } from "../lib/ledger";
import {
  balanceMessage,
  helpMessage,
  parseReply,
  record_incoming,
  send,
  shortRef,
  type Language,
} from "../lib/sms";
import { respondToOffer } from "./offers";
import { findPendingByRef, respondToRecord } from "../lib/confirmations";

export const smsRouter = Router();

smsRouter.use(requireAuth);

/**
 * ---------------------------------------------------------------------------
 * GET /api/sms
 *
 * The worker's message history, oldest first so it reads like a phone conversation.
 *
 * This is the page that stands in for the worker's actual handset. Nothing is
 * delivered by a telecom network; the messages are generated by the same code that
 * would send them, and the page is labelled as a simulation.
 * ---------------------------------------------------------------------------
 */
smsRouter.get("/", async (req, res) => {
  const user = req.user!;

  const messages = await prisma.smsMessage.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: "asc" },
    select: {
      id: true,
      direction: true,
      body: true,
      // Null unless the message was written in another language, so the page can
      // offer an English reading of it.
      bodyEn: true,
      language: true,
      kind: true,
      reference: true,
      createdAt: true,
    },
  });

  // Offers still waiting for a reply, so the page can show which codes are live.
  const pending = await prisma.workOffer.findMany({
    where: { workerId: user.id, status: "PENDING" },
    select: { id: true },
  });

  const pendingRefs = await Promise.all(
    pending.map(async (o) => {
      const link = await prisma.ledgerEntry.findFirst({
        where: { recordType: "OFFER", recordId: o.id },
        select: { currentHash: true },
      });
      return link ? shortRef(link.currentHash) : null;
    }),
  );

  return res.json({
    simulated: true,
    phone: user.phone,
    messages,
    awaitingReply: pendingRefs.filter((r): r is string => r !== null),
  });
});

const replySchema = z.object({
  body: z.string().min(1, "Type a reply"),
});

/**
 * ---------------------------------------------------------------------------
 * POST /api/sms/reply
 *
 * The worker "sends" an SMS back. This is what makes the SMS page a working
 * channel rather than a picture of one: typing "YES 4821" here accepts the offer
 * for real, seals the acceptance into the record chain, and locks the terms -
 * exactly as pressing Accept on the dashboard would.
 *
 * Both routes call the same `respondToOffer` function, so the two channels cannot
 * drift apart.
 * ---------------------------------------------------------------------------
 */
smsRouter.post("/reply", async (req, res) => {
  const parsed = replySchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: "Type a reply first" });
  }

  const user = req.user!;
  const raw = parsed.data.body;
  const reply = parseReply(raw);

  // Store what the worker sent, whatever it says, so the history is honest.
  await record_incoming({ userId: user.id, body: raw, kind: "REPLY", reference: reply.ref });

  const language = (user.language ?? "en") as Language;

  // Find which offer the code refers to. Only the worker's own offers are
  // considered, so a guessed code cannot touch someone else's contract.
  async function findOfferByRef(ref: string | undefined, status: string) {
    const candidates = await prisma.workOffer.findMany({
      where: { workerId: user.id, status },
      select: { id: true },
    });

    for (const c of candidates) {
      const link = await prisma.ledgerEntry.findFirst({
        where: { recordType: "OFFER", recordId: c.id },
        select: { currentHash: true },
      });
      if (link && shortRef(link.currentHash) === ref) return c.id;
    }
    // If there is exactly one pending offer, a reply with no code is
    // unambiguous, so accept it. Being strict here would fail a worker who
    // typed just "YES" - which is what most people would do.
    if (!ref && candidates.length === 1) return candidates[0]!.id;
    return null;
  }

  if (reply.intent === "ACCEPT" || reply.intent === "DECLINE") {
    const offerId = await findOfferByRef(reply.ref, "PENDING");

    if (!offerId) {
      const body = reply.ref
        ? `No offer waiting with code ${reply.ref}. Check the code and try again.`
        : `You have no offers waiting for a reply.`;
      await send({ userId: user.id, kind: "OFFER", language, body });
      return res.json({ understood: false, message: body });
    }

    const result = await respondToOffer({
      offerId,
      decision: reply.intent,
      via: "SMS",
    });

    return res.json({
      understood: true,
      intent: reply.intent,
      accepted: result.accepted,
      ref: result.ref,
    });
  }

  // OK / WRONG answer a work or payment record.
  if (reply.intent === "CONFIRM" || reply.intent === "REJECT") {
    const target = await findPendingByRef(user.id, reply.ref);

    if (!target) {
      const body = reply.ref
        ? `No record waiting with code ${reply.ref}. Check the code and try again.`
        : `You have more than one record waiting, or none. Reply with the code, for example: OK 1234`;
      await send({ userId: user.id, kind: "CONFIRM_WORK", language, body });
      return res.json({ understood: false, message: body });
    }

    // A worker rejecting by SMS cannot easily type their own figure, so the
    // record is flagged as disputed with the note recording that the correct
    // number is still to be collected. The officer follows up by phone, which is
    // what happens in practice anyway.
    const result = await respondToRecord({
      workerId: user.id,
      targetType: target.targetType,
      targetId: target.targetId,
      decision: reply.intent === "CONFIRM" ? "CONFIRM" : "REJECT",
      via: "SMS",
      workerValue: 0,
      note:
        reply.intent === "REJECT"
          ? "Rejected by SMS. The worker's own figure still needs to be collected by phone."
          : undefined,
    });

    if (!result.ok) {
      await send({ userId: user.id, kind: "CONFIRM_WORK", language, body: result.error });
      return res.json({ understood: false, message: result.error });
    }

    return res.json({
      understood: true,
      intent: reply.intent,
      confirmed: result.confirmed,
      ref: result.ref,
    });
  }

  if (reply.intent === "BALANCE") {
    const offers = await prisma.workOffer.findMany({
      where: { workerId: user.id, status: "ACCEPTED" },
      select: { id: true },
    });

    if (offers.length === 0) {
      const body = `You have no active work on record.`;
      await send({ userId: user.id, kind: "BALANCE", language, body });
      return res.json({ understood: true, intent: "BALANCE", message: body });
    }

    for (const o of offers) {
      const b = await computeBalance(o.id);
      if (!b) continue;
      const link = await prisma.ledgerEntry.findFirst({
        where: { recordType: "ACCEPT", recordId: o.id },
        select: { currentHash: true },
      });
      const ref = link ? shortRef(link.currentHash) : "0000";

      const balText = {
        siteName: b.siteName,
        dailyRate: b.dailyRate,
        daysWorked: b.daysWorked,
        paid: b.paid,
        balance: b.balance,
        ref,
      };

      await send({
        userId: user.id,
        kind: "BALANCE",
        reference: ref,
        language,
        body: balanceMessage(balText, language),
        bodyEn: balanceMessage(balText, "en"),
      });
    }

    return res.json({ understood: true, intent: "BALANCE" });
  }

  // Not understood: reply with the valid options rather than guessing, because a
  // wrong guess here would create a binding record from a misread message.
  const body = helpMessage(language);
  await send({ userId: user.id, kind: "OFFER", language, body, bodyEn: helpMessage("en") });
  return res.json({ understood: false, message: body });
});
